import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class MyReview {
  MyReview({
    required this.goodComment1,
    required this.goodComment2,
    required this.category,
    required this.picture,
    required this.option,
    required this.urlLink,
    required this.badComment1,
    required this.badComment2,
    required this.productName,
    required this.brand,
    required this.score,
    required this.purchasedDate,
    required this.price,
    required this.afterPurchase,
    required this.place,
    required this.placeName,
    required this.placeType,
  });



  String productName;
  String brand;
  int score;
  String purchasedDate;
  int price;
  int afterPurchase;
  String place;
  String placeType;
  String placeName;
  String category;
  String urlLink;
  String option;
  Image picture;
  String goodComment1;
  String goodComment2;
  String badComment1;
  String badComment2;


  static List<MyReview> reviews = [
    MyReview(
      place: 'Online',
      productName: '에어팟 2세대',
      brand: 'Apple',
      score: 95,
      purchasedDate: '2022-06-01',
      price: 189000,
      afterPurchase: 30,
      placeType: '쿠팡',
      placeName: '쿠팡',
      category: '이어폰',
      urlLink: 'https://www.coupang.com/vp/products/5114219077',
      option: '화이트',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '음질이 좋아서 음악을 듣는 즐거움이 배가됩니다',
      goodComment2: '외관 디자인이 매우 세련되고 고급스러워요',
      badComment1: '이어폰 끼워서 30분 이상 사용하면 귀가 아프네요',
      badComment2: '배터리 수명이 길지 않아서 자주 충전해야합니다',
    ),
    MyReview(
      place: 'Offline',
      productName: '블랙핑크 콘서트 티켓',
      brand: 'YG 엔터테인먼트',
      score: 100,
      purchasedDate: '2023-01-01',
      price: 150000,
      afterPurchase: 30,
      placeType: '예술의전당',
      placeName: '예술의전당',
      category: '공연',
      urlLink: '',
      option: '',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '라이브 공연을 직접 볼 수 있어서 너무 좋았습니다',
      goodComment2: '블랙핑크 멤버들의 퍼포먼스가 정말 멋있었어요',
      badComment1: '콘서트장에서 앉아있는 좌석이 조금 불편했어요',
      badComment2: '예술의전당 내부가 너무 복잡해서 길을 잃을뻔 했습니다',
    ),
    MyReview(
      place: 'Online',
      productName: '좋은 제품 1',
      brand: '브랜드 1',
      score: 80,
      purchasedDate: '2023-04-01',
      price: 10000,
      afterPurchase: 30,
      placeType: 'E-commerce',
      placeName: 'Amazon',
      category: '전자제품',
      urlLink: 'https://example.com/product1',
      option: '색상: 빨간색, 크기: M',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '제품 사용이 편리하고 간편하며 신속한 배송',
      goodComment2: '훌륭한 성능과 디자인',
      badComment1: '비싸다',
      badComment2: '이미 사용 중에 고장이 났음',
    ),
    MyReview(
      place: 'Offline',
      productName: '좋은 제품 2',
      brand: '브랜드 2',
      score: 90,
      purchasedDate: '2023-03-15',
      price: 20000,
      afterPurchase: 50,
      placeType: '마트',
      placeName: '홈플러스',
      category: '패션',
      urlLink: 'https://example.com/product2',
      option: '색상: 파란색, 크기: L',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '최고의 품질과 디자인, 편안하게 착용할 수 있음',
      goodComment2: '좋은 가격과 훌륭한 편의성',
      badComment1: '크기가 조금 작음',
      badComment2: '배송이 다소 늦었음',
    ),
    MyReview(
      place: 'Offline',
      productName: '좋은 제품 3',
      brand: '브랜드 3',
      score: 85,
      purchasedDate: '2023-05-01',
      price: 50000,
      afterPurchase: 15,
      placeType: '백화점',
      placeName: '롯데백화점',
      category: '의류',
      urlLink: 'https://example.com/product3',
      option: '색상: 검정색, 크기: S',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '깔끔하고 세련된 디자인',
      goodComment2: '부드러운 소재와 편안한 착용감',
      badComment1: '가격이 다소 비싸다',
      badComment2: '배송이 조금 늦었음',
    ),
    MyReview(
      place: 'Online',
      productName: 'Product 1',
      brand: 'Brand 1',
      score: 80,
      purchasedDate: '2023-04-01',
      price: 10000,
      afterPurchase: 30,
      placeType: 'E-commerce',
      placeName: 'Amazon',
      category: 'Electronics',
      urlLink: 'https://example.com/product1',
      option: 'Color: Red, Size: M',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '상품의 가격이 매우 합리적입니다.',
      goodComment2: '색상과 크기 등 다양한 옵션을 제공합니다.',
      badComment1: '배송이 다소 느리게 이루어졌습니다.',
      badComment2: '제품 포장이 불완전하여 상품이 손상될 우려가 있었습니다.',
    ),
    MyReview(
      place: 'Online',
      productName: 'LG Gram 16',
      brand: 'LG',
      score: 80,
      purchasedDate: '2022-11-10',
      price: 2000000,
      afterPurchase: 60,
      placeType: 'E-commerce',
      placeName: 'Coupang',
      category: 'Electronics',
      urlLink: 'https://www.coupang.com/vp/products/4098261350',
      option: '16GB RAM, 1TB SSD',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '가볍고 성능이 좋아 작업하기 편리합니다',
      goodComment2: '배터리가 오래가서 이동 시 편리합니다',
      badComment1: '디스플레이 화면이 좀 작은 느낌이 있습니다',
      badComment2: '가격이 다소 비싸다는 느낌이 드네요',
    ),
    MyReview(
      place: 'Offline',
      productName: 'Hyundai Kona EV',
      brand: 'Hyundai',
      score: 90,
      purchasedDate: '2022-08-15',
      price: 50000000,
      afterPurchase: 180,
      placeType: 'Car dealer',
      placeName: 'Hyundai Motor Studio',
      category: 'Automotive',
      urlLink: 'https://www.hyundai.com/kr/ko/vehicles/kona-electric',
      option: 'Premium package',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '운전감이 좋고 연비도 매우 우수합니다',
      goodComment2: '인테리어 디자인이 매우 세련되고 고급스럽습니다',
      badComment1: '리어씨트가 좀 작아 보긴 하지만 크게 불편하지 않습니다',
      badComment2: '가격이 다소 부담스러운 면이 있습니다',
    ),
    MyReview(
      place: 'Online',
      productName: 'MacBook Air',
      brand: 'Apple',
      score: 90,
      purchasedDate: '2023-04-01',
      price: 1200000,
      afterPurchase: 30,
      placeType: 'E-commerce',
      placeName: 'Apple Online Store',
      category: 'Electronics',
      urlLink: 'https://www.apple.com/macbook-air/',
      option: 'M1 chip, 8GB RAM, 512GB storage, Gold',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '성능이 빠르고 가볍습니다',
      goodComment2: '전체적인 디자인이 매우 멋집니다',
      badComment1: '가격이 다소 높습니다',
      badComment2: '포트 수가 부족합니다',
    ),
    MyReview(
      place: 'Online',
      productName: 'UltraSharp U3419W',
      brand: 'Dell',
      score: 85,
      purchasedDate: '2023-03-15',
      price: 800000,
      afterPurchase: 60,
      placeType: 'E-commerce',
      placeName: 'Dell Online Store',
      category: 'Electronics',
      urlLink: 'https://www.dell.com/en-us/shop/accessories/apd/210-arcj',
      option: '34-inch curved monitor',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '넓은 화면이 작업에 큰 도움이 됩니다',
      goodComment2: '이미지와 색의 표현이 매우 좋습니다',
      badComment1: '대형화면으로 인한 높은 가격입니다',
      badComment2: '설치 및 조립이 어려웠습니다',
    ),
    MyReview(
      place: 'Online',
      productName: '맥북 프로 2022',
      brand: 'Apple',
      score: 95,
      purchasedDate: '2022-05-01',
      price: 2500000,
      afterPurchase: 60,
      placeType: 'E-commerce',
      placeName: 'G-Market',
      category: 'Electronics',
      urlLink: 'https://www.apple.com/macbook-pro-14-and-16/',
      option: 'Space Gray, 16GB RAM, 1TB SSD',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '사용하기 편리하고 성능이 좋아서 매우 만족합니다.',
      goodComment2: '밝기와 색감이 정말 좋습니다.',
      badComment1: '가격이 다소 비쌉니다.',
      badComment2: '팬 소음이 조금 큽니다.',
    ),
    MyReview(
      place: 'Offline',
      productName: '오늘의 생과일 박스',
      brand: '프레시서울',
      score: 80,
      purchasedDate: '2023-04-25',
      price: 25000,
      afterPurchase: 3,
      placeType: 'Offline Store',
      placeName: '프레시서울 강남점',
      category: 'Grocery',
      urlLink: 'https://www.freshseoul.co.kr/',
      option: '',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '신선한 과일이 많아서 좋았습니다.',
      goodComment2: '포장이 깔끔해서 만족합니다.',
      badComment1: '가격이 다른 마트보다 조금 비쌉니다.',
      badComment2: '배송비가 없어서 편리하지만 가게에서 직접 사는 것보다는 비쌉니다.',
    ),
    MyReview(
        place: 'Online',
        productName: '배달의민족 피자',
        brand: '배달의민족',
        score: 70,
        purchasedDate: '2023-04-30',
        price: 25000,
        afterPurchase: 2,
        placeType: 'Food Delivery',
        placeName: '배달의민족',
        category: 'Food',
        urlLink: 'https://www.deliveryhero.co.kr/ko/',
        option: '콤비네이션 라지사이즈',
        picture: Image.network('https://via.placeholder.com/150'),
    goodComment1: '배달이 빠르고 맛은 그럭저럭 괜찮았습니다.',
    goodComment2: '할인 이벤트 때 마다 주문합니다.',
    badComment1: '토핑이 너무 적게 올라와서 아쉽습니다.',
    badComment2: '가격이 다른 피자 배'
    ),
    MyReview(
      place: '오프라인',
      productName: '갤럭시 S25',
      brand: '삼성',
      score: 90,
      purchasedDate: '2023-04-15',
      price: 1300000,
      afterPurchase: 15,
      placeType: '전자제품 매장',
      placeName: '전자랜드',
      category: '전자제품',
      urlLink: 'https://example.com/product2',
      option: '색상: 블랙, 용량: 256GB',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '디자인이 세련되고 사용하기에 매우 편리합니다',
      goodComment2: '카메라 성능이 뛰어나서 사진 찍기 좋아요',
      badComment1: '폰 트레이가 조금 불안정해서 걱정이 되네요',
      badComment2: '배터리 수명이 더 길면 완벽할 것 같습니다',
    ),
    MyReview(
      place: '온라인',
      productName: '코드리스 청소기',
      brand: 'LG전자',
      score: 75,
      purchasedDate: '2023-03-20',
      price: 450000,
      afterPurchase: 40,
      placeType: 'E-commerce',
      placeName: 'G마켓',
      category: '가전제품',
      urlLink: 'https://example.com/product3',
      option: '색상: 화이트, 모델: A9',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '청소 편의성이 크게 향상되어 만족스럽습니다',
      goodComment2: '충전 시간이 짧아서 일상 사용이 편리해요',
      badComment1: '먼지통 용량이 작아 자주 비워야 하는게 번거롭습니다',
      badComment2: '모터 소음이 좀 큰 편이라 조금 거슬리네요',
    ),MyReview(
      place: '오프라인',
      productName: '갤럭시 S25',
      brand: '삼성',
      score: 90,
      purchasedDate: '2023-04-15',
      price: 1300000,
      afterPurchase: 15,
      placeType: '전자제품 매장',
      placeName: '전자랜드',
      category: '전자제품',
      urlLink: 'https://example.com/product2',
      option: '색상: 블랙, 용량: 256GB',
      picture: Image.network('https://via.placeholder.com/150'),
      goodComment1: '갤럭시 S25 디자인이 세련되어 사용하기 매우 편리하고 만족스러워요',
      goodComment2: '갤럭시 S25 카메라 성능이 뛰어나 사진 찍는 것이 정말 즐거워요',
      badComment1: '갤럭시 S25 폰 트레이가 조금 불안정해 걱정되기도 합니다',
      badComment2: '갤럭시 S25 배터리 수명이 좀 더 길었다면 완벽했을 것 같아요',
    ),
    MyReview(
      place: '온라인',
      productName: '코드리스 청소기',
      brand: 'LG전자',
      score: 75,
      purchasedDate: '2023-03-20',
      price: 450000,
      afterPurchase: 40,
      placeType: 'E-commerce',
      placeName: 'G마켓',
      category: '가전제품',
      urlLink: 'https://example.com/product3',
      option: '색상: 화이트, 모델: A9',
      picture:  Image.network('https://via.placeholder.com/150'),
      goodComment1: 'LG 코드리스 청소기 편의성이 크게 향상되어 일상생활이 편해졌어요',
      goodComment2: 'LG 코드리스 청소기 충전 시간이 짧아 사용하기 정말 편리해요',
      badComment1: 'LG 코드리스 청소기 먼지통 용량이 작아 자주 비워야 하는게 번거로워요',
      badComment2: 'LG 코드리스 청소기 모터 소음이 좀 큰 편이라 조금 거슬립니다',
    ),
  ];
}
